### ISSUE TITLE
Make a new 1.3 release

### ISSUE THREAD

**Issue by natami** [apptik/MultiSlider#17]
Please do a new 1.3 release :)

**Comment by djodjoni** [comment]
I really want to :) I was working on #11 and this is the only one which I want to complete before 1.3 release. I haven't touched it for a long time, but I plan to finish this up next week and then release 1.3. So Ill plan the release on the 17th

**Comment by djodjoni** [comment]
due to a very busy schedule the release is postponed to 31st of August
