### ISSUE TITLE
Increase Height Of ProgressBar

### ISSUE THREAD

**Issue by maheshordex** [apptik/MultiSlider#20]
How to increase height of slider progressbar

**Comment by djodjoni** [comment]
'slider progressbar' could be misleading however you have 2 customizable components which you might be interested in:
1)  the track
2) the ranges 

you have as many ranges as the number of thumbs.
For the track and the ranges you can set any drawable.

for the track you can set in in the layout.xml for example: `android:track="@drawable/example_scrubber_secondary_holo"`

for the tracks example: `app:range="@drawable/example_scrubber_secondary_holo"`

you can also set different range drawables and you can set for the range 1 and 2 from the xml in a similar way using 'app:range2' and 'app:range2'

you can find more examples here: https://github.com/apptik/MultiSlider/blob/master/example/src/main/res/layout/fragment_multi_slider_range.xml

 BTW for Questions please use http://stackoverflow.com/ with tag 'MultiSlider'

**Comment by vvbhandare** [comment]
But it shows greyish color in the background

**Comment by djodjoni** [comment]
@vvbhandare can you be more specific please :
 1) what do you try to achieve (expected outcome)
2) how do you try to achieve it (xml + code)
