### ISSUE TITLE
How to set right(max) thumb on right

### ISSUE THREAD

**Issue by dmelechow** [apptik/MultiSlider#21]
How to set right(max) thumb on right? I want to align right  max thumb. I setMax(296), but max thumb sets on the hundredth position. 
![21sdkrsqppm](https://cloud.githubusercontent.com/assets/11187627/17989694/f6fed036-6b37-11e6-97bd-147e689680d2.jpg) in advance, thank you)

**Comment by djodjoni** [comment]
setMax for both the slider and a thumb will set the maximum available value but not change a thumb value unless the value is outside the limit then it will be set to the maximum.

In your case you need to call setValue() on the second thumb:

`multiSlider.getThumb(1).setValue(296);`

**Comment by dmelechow** [comment]
@djodjoni  Thanks for answer, very helpful)
