### ISSUE TITLE
Does support secondary progress?

### ISSUE THREAD

**Issue by AmirHadifar** [apptik/MultiSlider#23]
Hello and Thanks for awsome lib. I want to know is it possible to add secondary progressBar to your slider?

**Comment by djodjoni** [comment]
secondary progress can be achieved with customizing the thumb range.
we have **track** and **thumbs** every thumb has a **range** which is from previous thumb or the beginning of the track to the thumb itself. 
Every range can have custom drawable which can be set programmatically:

`        multiSlider.getThumb(2).setRange( new ColorDrawable(0xFFFF0000));
`
this will set red color between the second the the third thumb.

default range drawable can be set from the xml:
`            app:rangeColor="@android:color/holo_green_dark"
`

and custom range drawables for the first and second thumb can also be set from the xml:
`            app:range1="@drawable/example_scrubber_secondary_holo"
            app:range2="@drawable/example_scrubber_secondary_holo"
`

Note that if you want to hide the thumb so it looks like a bar only you can the the thumb to invisible:
`        multiSlider.getThumb(2).setInvisibleThumb(true);
`

you can check examples for more info :)
