### ISSUE TITLE
Update Maven build to include onStartTrackingTouch functionality

### ISSUE THREAD

**Issue by Nicrob64** [apptik/MultiSlider#28]
The current version in Maven central (1.2) doesn't have the support for (onStart/onStop)TrackingTouch. 

It is still usable through jitpack and using the commit hash, but it would be nice if this was changed to either be reflected in the readme or have the maven build updated to include these changes.

**Comment by djodjoni** [comment]
1.3 will be relesed next week to maven central. btw i split the interfaces for compatibility reasons and easier to use lambda when using thumb value chane only. change log and java docs will be included with the release also.
