### ISSUE TITLE
library draw correct only from API 23 and above

### ISSUE THREAD

**Issue by bmx666** [apptik/MultiSlider#47]
Screenshots from emulators:

![screenshot1](https://cloud.githubusercontent.com/assets/2761506/21965706/53ca0fe8-db76-11e6-82f6-dc58591939ec.png)
![screenshot2](https://cloud.githubusercontent.com/assets/2761506/21965704/53c8951e-db76-11e6-8758-db71e61a82d6.png)
![screenshot3](https://cloud.githubusercontent.com/assets/2761506/21965703/53c86008-db76-11e6-9f1e-ad9da9333579.png)
![screenshot4](https://cloud.githubusercontent.com/assets/2761506/21965705/53c8e6fe-db76-11e6-9767-427ab54ebf68.png)

![screenshot_api21_0](https://cloud.githubusercontent.com/assets/2761506/21965857/45ec3c18-db79-11e6-8e09-23a360adb781.png)
![screenshot_api21_1](https://cloud.githubusercontent.com/assets/2761506/21965858/45edf44a-db79-11e6-9bac-050fe86abd0b.png)

**Comment by djodjoni** [comment]
this is an issue with default drawables and the background for the theme on the api16 examples.
Ill push a fix shortly. however you can put your custom drawables and themes as you like

**Comment by ANGerz** [comment]
Hello, I would like to know if you got updates on this issue.
Thanks.

**Comment by djodjoni** [comment]
It is partially fixed but didn't gave time to followup. Ill probably wrapup a minor release next week

**Comment by joacimfloren** [comment]
Hey, is there any updates on this issue?
Thanks!

**Comment by MikeW1986** [comment]
*push*
some news about the update?

**Comment by bmx666** [comment]
I use hack for get all drawables correct like in SeekBar:

Helper class for extract Thumb from SeekBar

```java
public class HFAppCompatSeekBar extends AppCompatSeekBar {

    public HFAppCompatSeekBar(Context context) {
        super(context);
    }

    public HFAppCompatSeekBar(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    public HFAppCompatSeekBar(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
    }

    @Override
    public Drawable getThumb() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN)
            return super.getThumb();

        // Using reflection, don't override setThumb
        // because others methods in AbsSeekBar change mThumb
        try {
            // HFAppCompatSeekBar -> AppCompatSeekBar -> SeekBar -> AbsSeekBar
            Class<?> cls = this.getClass().getSuperclass().getSuperclass().getSuperclass();
            Field f = cls.getDeclaredField("mThumb");
            f.setAccessible(true);
            return (Drawable) f.get(this);
        } catch (NoSuchFieldException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        }
        return null;
    }
}
```

Somewhere in code
```java
mMySeekBar = (MultiSlider) view.findViewById(R.id.myseekbar);
            // HACK: for draw track
            if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.KITKAT) {
                HFAppCompatSeekBar mTempSeekBar = new HFAppCompatSeekBar(ctx);
                mMySeekBar.setTrackDrawable(mTempSeekBar.getProgressDrawable());
            }
            for (int i = 0; i < 2; ++i) {
                HFAppCompatSeekBar mTempSeekBar = new HFAppCompatSeekBar(ctx);
                mMySeekBar.getThumb(i).setThumb(mTempSeekBar.getThumb());
            }
            // HACK: for draw range
            if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.KITKAT) {
                HFAppCompatSeekBar mTempSeekBar = new HFAppCompatSeekBar(ctx);
                mTempSeekBar.setProgress(100);
                mMySeekBar.getThumb(1).setRange(mTempSeekBar.getProgressDrawable());
            }
```

**Comment by djodjoni** [comment]
@bmx666  this works partially as some cases and states are not properly handled .

I have pushed https://github.com/apptik/MultiSlider/tree/issue47 
where I did some cleanup and fix most of the issues some time ago. 
There is still an issue with api21 with the styles. 
I believe related to colorControlActivated and colorControlHighlight.
You can check it out if you have time.
 I will also try to solve it but not before the end of the week as I am terribly busy.

**Comment by yeray697** [comment]
Hi, I'm using 1.3.1-SNAPSHOT, but it's still being draw as a white line and transparent color when user touches, did I skip some step?

**Comment by bmx666** [comment]
Hi @yeray697, can you give more info and share with code?

**Comment by yeray697** [comment]
Sure
I have this on my main style:
```
    <...
        <item name="multiSliderStyle">@style/Widget.MultiSlider</item>
    .../>
    <style name="Widget.MultiSlider" parent="android:Widget">
        <item name="colorControlActivated">@color/colorPrimaryDark</item>
        <item name="colorControlHighlight">@color/colorPrimaryDark</item>
    </style>
```
(colorPrimaryDark = green)

**Comment by bmx666** [comment]
@yeray697, without colorControlActivated and colorControlHighlight attrs it's work correctly?

**Comment by yeray697** [comment]
No, it's still white and transparent. I've also tried without style and I got the same result

**Comment by bmx666** [comment]
@yearay697, which API are you use?

**Comment by yeray697** [comment]
```
compileSdkVersion 26
    buildToolsVersion '26.0.2'
    defaultConfig {
        applicationId ""
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 
        versionName ""
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true
    }
```

**Comment by bmx666** [comment]
@yeray697, you have similar issue on all emulators/devices (api 21/22/23/25/26/27) ?

**Comment by yeray697** [comment]
It's working on emulator with api 21, but there's another style problem (or I don't know how to change it), when I touch, appears a red transparent circle and I would like to change it.
In api 23 this circle works good, it appears with the color I want

**Comment by bmx666** [comment]
@yeray697, checked on API 21, all ok.
You must change **colorAccent** for change multislider style. For ripple effect see issue #65

**Comment by bmx666** [comment]
@yeray697 for API 19 and lower you should use holo style. If you need material style you can use hack with seekbar to get style and apply it to multislider (see my comment above)

**Comment by yeray697** [comment]
Nice, thank you, I haven't realized that Holo was neccesary < 19

By the way, I think you have two unused images (or I haven't found where are used): `MultiSlider/holo-style/src/main/res/drawable-hdpi/seek_thumb_normal.png` and `MultiSlider/holo-style/src/main/res/drawable-hdpi/seek_thumb_pressed.png`
