### ISSUE TITLE
Error in UI designer when following usage instructions

### ISSUE THREAD

**Issue by ojotoxy** [apptik/MultiSlider#51]
"Missing styles. Is the correct theme chosen for this layout? Failed to find style 'multiSliderStyle' in current theme "

Despite this, the UI element displays fine in the UI designer, and it runs properly.
I would love to clean up this error and update the usage instructions to avoid it, but I'm not sure what's wrong.

This is my XML:

`
            <io.apptik.widget.MultiSlider
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_weight="1"
                app:thumbNumber="2"
                app:stepsThumbsApart="1"
                app:drawThumbsApart="true"
                android:id="@+id/tiltRange" />
`

**Comment by bmx666** [comment]
Try edit styles in your project

in **res/values/styles.xml**

```xml
<style name="AppTheme" parent="...">
    <item name="multiSliderStyle">@style/Widget.MultiSlider</item>
</style>

<style name="Widget.MultiSlider" parent="android:Widget">
    <item name="android:background">@color/transparent</item>
    <item name="android:thumb">@drawable/multislider_thumb_material</item>
</style>
```

in **res/values-v21/styles.xml**

```xml
<style name="Widget.MultiSlider" parent="android:Widget">
    <item name="android:background">@drawable/control_background_multi_material</item>
    <item name="android:thumb">@drawable/multislider_thumb_material_anim</item>
</style>
```

**Comment by ojotoxy** [comment]
Thanks, this helped.

Seems like default is the material style, this is all that I needed to add:


```
<style name="AppTheme" parent="...">
    <item name="multiSliderStyle">@style/Widget.MultiSlider</item>
</style>

<style name="Widget.MultiSlider" parent="android:Widget">
</style>
```


And to use the holo style, just this:

```
<style name="AppTheme" parent="...">
    <item name="multiSliderStyle">@style/sliderHoloStyle</item>
</style>
```

After adding this to gradle:

`
    compile 'io.apptik.widget:multislider-holo:1.3'
`

I think it would help to add these notes to the doc. :)

**Comment by djodjoni** [comment]
correct indeed :) Will be added in the readme. the best place I can think of now is the "Usage" section. 
PR is always welcome of course  :)
