### ISSUE TITLE
How to setProgress ?

### ISSUE THREAD

**Issue by OriginApp-Shri** [apptik/MultiSlider#53]
I am trying to set the progress for single seekbar. I am unable to add progress by default to seekbar. Can you please help me with that ?

**Comment by djodjoni** [comment]
` multiSlider.getThumb(0).setValue(50)`
check [examples](https://github.com/apptik/MultiSlider/blob/master/example/src/main/java/io/apptik/widget/example/multislider/MultiSliderFragmentRange.java#L172) 

Btw GitHub is preferred for issues for questions please use in [stackoverflow](http://stackoverflow.com) and tag it [multislider]

**Comment by FarshidABZ** [comment]
I have a problem with setValue programmatically, it doesn't work in my case 

`binding.distanceSlider.getThumb(0).value = 10`
