### ISSUE TITLE
App crashed, if setTickStart called before setTickEnd

### ISSUE THREAD

**Issue by Syjgin** [apptik/MultiSlider#54]
First, I'm trying to call methods in this order:
```
rangeBar.setTickStart(200);//tick end is initially set to 0, if no xml value specified, so we have invalid index
rangeBar.setTickEnd(3000);
rangeBar.setTickHeight(1);
```
Maybe, if setTickStart cannot be called before setTickEnd, it's better to create only one public method so set both start and end ticks?

**Comment by djodjoni** [comment]
The strange thing is that it compiles :) neither of those methods exist in MultiSlider. 
It seems you use of the many other range bars that appeared. Please post your issue there :)
