### ISSUE TITLE
Issue with slider on API 22

### ISSUE THREAD

**Issue by proft** [apptik/MultiSlider#61]
Hello!

I use ``compile 'io.apptik.widget:multislider:1.3'`` and have issue on API 22 with track. 
Look at pic: https://ibb.co/dENuSk

**Comment by Prasanna-Datha** [comment]
Yup! Same here. The slider track is very thick in appearance.

**Comment by bmx666** [comment]
Hi, @proft and @Prasanna-Datha 
This issue was fixed, see #47
And try use the latest snapshot
```gradle
// in project build.grade
android {
    repositories {
        mavenCentral()
        maven {
            url "https://oss.sonatype.org/content/repositories/snapshots"
        }
    }
}

dependencies {
    compile 'io.apptik.widget:multislider:1.3.1-SNAPSHOT'
}
```

**Comment by perasoft** [comment]
Hey man. You keep closing this issue but i have tried the solution u provided it doesnt work. Please help me maybe i am getting something wrong.

**Comment by bmx666** [comment]
Hi @perasoft, Most of the people opened issues and don't response anything after month or after half year. I checked many times this issue on master branch.
1. You look the issue #47?
2. Download latest master branch and compile with your app
3. if you still have a trouble please attach part of xml-layout and source code for multislider, screenshots and API level of Android device/emulator.

P.S. waiting for answer
