### ISSUE TITLE
Incorrect layout on API 22

### ISSUE THREAD

**Issue by Nfear** [apptik/MultiSlider#64]
styles.xml:

    <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="multiSliderStyle">@style/Widget.MultiSlider</item>
    </style>

    <style name="Widget.MultiSlider" parent="android:Widget" />

Use the following without setting other attributes programmatically or in xml:

    <io.apptik.widget.MultiSlider
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

Output:

![screen shot 2017-08-09 at 10 43 11](https://user-images.githubusercontent.com/4550589/29112881-9788d05a-7cef-11e7-9e68-1f0509c63cc4.png)

**Comment by bmx666** [comment]
@Nfear, you used master branch with the latest commit or version 1.3?

**Comment by Nfear** [comment]
@bmx666 I used version 1.3

**Comment by bmx666** [comment]
@Nfear, this issue was fixed in https://github.com/apptik/MultiSlider/commit/669884c3bd24cc5c8b130700aed91cf5ec541662. Check on master branch, this issue should be fixed

**Comment by bmx666** [comment]
https://github.com/apptik/MultiSlider/issues/61
