### ISSUE TITLE
Material Design with AppCompat on API <21

### ISSUE THREAD

**Issue by cypressious** [apptik/MultiSlider#68]
I configured the widget according to the ReadMe.

```xml
<style name="MyTheme" parent="Theme.AppCompat.Light.DarkActionBar">
    ...
    <item name="multiSliderStyle">@style/Widget.MultiSlider</item>
</style>

<style name="Widget.MultiSlider" parent="android:Widget">
</style>
```

Now, on API 21+, it looks perfect. However, on API <21, the widget is completely transparent. Nothing is drawn, but it's actually useeable. Did I miss something or do I have to use Holo on API <21?

**Comment by cypressious** [comment]
Btw, this is how the example app looks on API 16

![grafik](https://user-images.githubusercontent.com/1191816/29975445-a33ed0ee-8f36-11e7-9197-ef90b15c6da9.png)

**Comment by bmx666** [comment]
@cypressious, have you seen these issues?
#47 #61 #64

**Comment by bmx666** [comment]
No response
