### ISSUE TITLE
Put a custom label above thumb when thumb is moved

### ISSUE THREAD

**Issue by sandransoria** [apptik/MultiSlider#69]
Hi,

I use a MultiSlider with three thumbs (with custom thumb icons) and would like to put a label below (or above) the thumb which is currently tragged and moved. I tried to use the boundary of the thumb drawable to get the position of the thumb and put a label at this position:

```
//get value
int x = myThumb.getThumb().getBounds().left
//position linear layout with label
labelWrapper.setX(x);

```

But the returned value is slightly shifted to the right.

I also tried to use the approach shown in https://github.com/apptik/MultiSlider/pull/49/commits/a5209ab0d710c1eb106914d2230dc44b64b9f163
```

int pos_x = mCenterThumb.getThumb().getBounds().centerX();
//offset it half the width of the linear layout with the label
int offset = labelWrapper.getWidth() / 2;
pos_x -= offset;

```
But even with this, the label remains shifted to the right.

What i want:
![seekbar1](https://user-images.githubusercontent.com/29749255/30963087-81ff0d74-a44c-11e7-9224-0ae8fb2383d8.png)

What it get:
![seekbar1](https://user-images.githubusercontent.com/29749255/30964569-2d6d0e68-a452-11e7-82a7-ff239d135186.png)

The problem also occurs if I use the "vanilla" thumb icons.

Any ideas how I can make this work? Or is there any library functionality I didn't noticed so far to get a custom label near the thumb?

EDIT: I already saw that there is a possibility to show text above the thumb.
But I don't need to show the value all the time (only while the thumb is moved) and I would like to have a custom drawable as background.

**Comment by bmx666** [comment]
@sandransoria, it's same issue #50 ?

**Comment by sandransoria** [comment]
thank you! I will check this out.
