### ISSUE TITLE
Could not import using gradle compile

### ISSUE THREAD

**Issue by pickledDachshund** [apptik/MultiSlider#7]
I added compile 'io.apptik.widget:multislider:1.2.0' in the gradle build file for my app module and I get an error:

> Error:(25, 13) Failed to resolve: io.apptik.widget:multislider:1.2.0
> <a href="openFile:/Users/limmor1/TestMultiSlider6/app/build.gradle">Show in File</a><br><a     href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

p.s. quite new to importing other projects, maybe stupid question

**Comment by razvanaschilean** [comment]
add just 'io.apptik.widget:multislider:1.2'

**Comment by djodjoni** [comment]
correct! i will change the readme.md

**Comment by amna-mirza-11** [comment]
Adding compile 'io.apptik.widget:multislider:1.2' in gradle file, generate an error.

**Comment by djodjoni** [comment]
could you open up a new issue as it seems it is and add what exactly is the error from gradle and your full gradle script.
