### ISSUE TITLE
Setting layout padding causes the Range - TrackBar shift to look deceiving 

### ISSUE THREAD

**Issue by nbaua** [apptik/MultiSlider#71]
Hi,

I guess, I found a possible bug/issue in the implementation.
If I set the layout padding to provide some puff around the MultiSlider it causes a deceiving shift in the inner TrackBar [See Image](https://drive.google.com/file/d/1rpBlWGZj720v762_uX1AMBXq2nJUHOkz/view?usp=sharing).

Please have a look at it at your earliest, and If any remedy suggest at earliest.

(BTW, I am using the **layout_marginTop** and **layout_marginBottom**, now, which resolves this issue, however I was wondering, never seen this behavior with the android slider, so if you could please look in)

**Comment by Fanthomo** [comment]
Hallo,
I have similiar problem with bottom padding, I want to extend touch area to better user experience by padding, Top padding is working ok.

Please take a look at it, thanks.

**Comment by Fanthomo** [comment]
@bmx666 hi, please look at my request to fix the issue
