### ISSUE TITLE
Track Height varies with Android SDK

### ISSUE THREAD

**Issue by iaindownie** [apptik/MultiSlider#72]
Could this library benefit from a setTrackThickness(int thicknessInDp) method?

Android 5.1 inflates the track line to the height of the thumbs, while Android 7.0 shows a cleaner, narrow track line. A setTrackThickness() method could control this better?

5.1
![screenshot_2017-12-12-13-21-27](https://user-images.githubusercontent.com/5167233/33890377-facf3f42-df4a-11e7-90a1-9d6fb5cd9b34.png)

7.0
![screenshot_1513089708](https://user-images.githubusercontent.com/5167233/33890420-24deb150-df4b-11e7-8a48-8493d1467f80.png)

**Comment by bmx666** [comment]
Hi, @iaindownie
You can see issues #47, #61, #64

**Comment by bmx666** [comment]
@iaindownie issue was solved?
