### ISSUE TITLE
The Thumb is not updated for the OnThumbValueChangeListener

### ISSUE THREAD

**Issue by CsabaZz** [apptik/MultiSlider#74]
Can we change the order of these calls please, so the thumb is updated and **then** call we the listener? Thus we will know the new parameters of the Thumb, like the new left/right position of the thumb.

So,

        if (hasOnThumbValueChangeListener()) {
            mOnThumbValueChangeListener.onValueChanged(this, thumb, mThumbs.indexOf(thumb), thumb
                    .getValue());
        }
        updateThumb(thumb, getWidth(), getHeight());

Should be

        updateThumb(thumb, getWidth(), getHeight());
        if (hasOnThumbValueChangeListener()) {
            mOnThumbValueChangeListener.onValueChanged(this, thumb, mThumbs.indexOf(thumb), thumb
                    .getValue());
        }

**Comment by bmx666** [comment]
Hi @CsabaZz,
You can change thumb's props before redraw it. For example set min/max values depend on logic of your app.

**Comment by bmx666** [comment]
In your case you can extend logic **OnValueChangeBefore** and **OnValueChangeAfter**

**Comment by CsabaZz** [comment]
@bmx666 I don't find those interfaces. Can you help me please? I'm using the v1.3 version.

**Comment by bmx666** [comment]
1. Use latest master branch v1.3.1-SNAPSHOT, v1.3 is deprecated
2. Fix library interface:
```java
    public interface OnThumbValueChangeListener {
        void onValueChangedBefore(MultiSlider multiSlider, MultiSlider.Thumb thumb, int thumbIndex, int
                value);
        void onValueChangedAfter(MultiSlider multiSlider, MultiSlider.Thumb thumb, int thumbIndex, int
                value);
}
```
3. Add post fixes in lib:
```java
private synchronized void setThumbValue(Thumb thumb, int value, boolean fromUser) {
        //...
        if (hasOnThumbValueChangeListener()) {
            mOnThumbValueChangeListener.onValueChangedBefore(this, thumb, mThumbs.indexOf(thumb), thumb.getValue());
        }
        updateThumb(thumb, getWidth(), getHeight());
        if (hasOnThumbValueChangeListener()) {
            mOnThumbValueChangeListener.onValueChangedAfter(this, thumb, mThumbs.indexOf(thumb), thumb.getValue());
        }
}
```
4. Add post fixes in lib:
```java
    public static class SimpleChangeListener implements OnThumbValueChangeListener,
            OnTrackingChangeListener {

        @Override
        public void onValueChangedBefore(MultiSlider multiSlider, Thumb thumb, int thumbIndex, int
                value) {
        }

        @Override
        public void onValueChangedAfter(MultiSlider multiSlider, Thumb thumb, int thumbIndex, int
                value) {
        }

        @Override
        public void onStartTrackingTouch(MultiSlider multiSlider, Thumb thumb, int value) {
        }

        @Override
        public void onStopTrackingTouch(MultiSlider multiSlider, Thumb thumb, int value) {
        }
}
```
5. Use **onValueChangedAfter** in your app

**Comment by bmx666** [comment]
Maybe you looking something this #50?

**Comment by bmx666** [comment]
I merged branch **thumb-binder-dev** with master, you can check

**Comment by CsabaZz** [comment]
Sounds similar...

**Comment by CsabaZz** [comment]
Added 

        compile 'io.apptik.widget:multislider:1.3.1-SNAPSHOT'

but does not seem that the underline code has changed, I can compile the project without the need of change the implementation of the listener as you suggested. :(

**Comment by bmx666** [comment]
@CsabaZz, download source code of library and include in your app.

**Comment by CsabaZz** [comment]
OK, thx. I thought it's available as gradle dependency.

**Comment by bmx666** [comment]
@CsabaZz, for **thumb-binder-dev** branch you don't need change library interface. Just bind textview to thumb (see example)

**Comment by CsabaZz** [comment]
I'll do it, thanks!

**Comment by CsabaZz** [comment]
Sorry for not answering earlier. Seems working fine with the binding code, and I could remove the call of translationX method since it is done by the lib - it means much cleaner code. :)
