### ISSUE TITLE
MultiSlider's range color doesnt show on API 19 (kitkat) 

### ISSUE THREAD

**Issue by Yashshree** [apptik/MultiSlider#88]
By default range color is white on API 19 , it is working fine on API above 19 , I have specified rangecolor property still it is not working on API 19 (kitkat). Please help
![scv_15244613095578139704287286709145](https://user-images.githubusercontent.com/18566885/39108408-b21f2d36-46e5-11e8-8a06-58961753bb53.jpg)

**Comment by IslamKhSh** [comment]
I also have the same problem

**Comment by Yashshree** [comment]
This is how i have solved it.
Add library as module .
add horizontal line drawable of whatever color you want in its drawable folder
Now by default library has used white line drawable (for API below 19) so just change that default drawable with your drawable and it will work for kitkat.
go to drawable-> multislider_track_material package-> multislider_track_material.xml -> change drawable attribute of layer-list tag
you are done.
