### ISSUE TITLE
How to make this seek with audio?

### ISSUE THREAD

**Issue by MarcVertigo** [apptik/MultiSlider#93]
Is there a slidingSeekBar.setOnSeekBarChangeListener type of function like with regular android seekBar?

**Comment by MarcVertigo** [comment]
@bmx666 Hey thanks for the response. OnThumbValueChangeListener is when you drag the thumb right? I'm looking to seek the thumb with music.

**Comment by bmx666** [comment]
@MarcVertigo look at README section **in the activity/fragment code add**
