### ISSUE TITLE
Kotlin setOnThumbValueChangeListener IllegalAccessError

### ISSUE THREAD

**Issue by FarshidABZ** [apptik/MultiSlider#96]
Hi 
I'm working with MultiSlider on thumb binder branch. 
On Android 6.0 when I call setOnThumbValueChangeListener I got : "ava.lang.IllegalAccessError: Illegal class access:" error and application crashed. 

is it because of kotlin?

I couldn't find a solution for it.

could you help me?

**Comment by bmx666** [comment]
@FarshidABZ this parent commit should fix issue 55e94f17bbac0ad94d7d9741db606a9f4f9e702f
Can you check this?

**Comment by FarshidABZ** [comment]
@bmx666  Yes, it helps, but I think it needed to merge with thumb binder branch. 
Thanks

**Comment by bmx666** [comment]
@FarshidABZ it already it thumb-binder-dev branch
